apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/John-Roger-Org/helm-chart-argocd.git
    targetRevision: HEAD
    path: templates
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-server

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true